const state={works:[],filtered:[],filter:"all",paused:false,offsets:[],last:0};
const ROWS=13;
const SPEED=18;
const FALLBACK_IMAGE="images/wakayama-001.jpg";
const rows=document.getElementById("worksRows"),pauseButton=document.getElementById("pauseButton"),modal=document.getElementById("photoModal"),modalImage=document.getElementById("modalImage"),modalTitle=document.getElementById("modalTitle"),modalCounter=document.getElementById("modalCounter"),modalDescription=document.getElementById("modalDescription"),views=document.querySelectorAll("[data-view]"),routeLinks=document.querySelectorAll("[data-route]");
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function showView(route){const target=["author","works","archive","contact"].includes(route)?route:"home";views.forEach(v=>v.hidden=v.dataset.view!==target);routeLinks.forEach(a=>a.classList.toggle("active",a.dataset.route===target));document.getElementById("mobileMenu")?.classList.remove("open");document.body.classList.remove("view-enter");void document.body.offsetWidth;document.body.classList.add("view-enter");window.scrollTo({top:0,behavior:"smooth"})}
routeLinks.forEach(a=>a.addEventListener("click",e=>{const r=a.dataset.route;if(!r)return;e.preventDefault();history.pushState({},"",`#${r}`);showView(r)}));window.addEventListener("hashchange",()=>showView(location.hash.slice(1)));window.addEventListener("popstate",()=>showView(location.hash.slice(1)));
function splitRows(items){const grouped=Array.from({length:ROWS},()=>[]);items.forEach((item,index)=>grouped[index%ROWS].push(item));return grouped.filter(row=>row.length)}
function render(){state.filtered=state.filter==="all"?state.works:state.works.filter(x=>x.category===state.filter);state.offsets=Array(ROWS).fill(0);rows.innerHTML=splitRows(state.filtered).map((row,index)=>`<div class="carousel-row row-reveal" style="--row-delay:${index*45}ms"><div class="carousel-row-track">${row.map(x=>`<article class="work-card" data-id="${esc(x.id)}"><img src="${esc(x.image)}" alt="${esc(x.title)}" loading="lazy"><div class="work-card-info"><h3 class="work-card-title">${esc(x.title)}</h3><p class="work-card-description">${esc(x.description)}</p><div class="work-card-meta"><span>${esc(x.location)}</span><span>${esc(x.year)}</span></div></div></article>`).join("")}</div></div>`).join("");rows.querySelectorAll(".work-card").forEach(card=>card.addEventListener("click",()=>openModal(card.dataset.id)));rows.querySelectorAll(".work-card img").forEach(img=>img.addEventListener("error",()=>{if(img.src.endsWith(FALLBACK_IMAGE))return;img.src=FALLBACK_IMAGE},{once:true}))}
function animate(t){if(!state.last)state.last=t;const dt=Math.min(t-state.last,64);state.last=t;if(!state.paused&&!document.hidden)rows.querySelectorAll(".carousel-row").forEach((row,i)=>{const track=row.querySelector(".carousel-row-track"),w=track?.scrollWidth||0;if(!w)return;const max=Math.max(0,w-row.parentElement.clientWidth);if(!max)return;const direction=i%2?-1:1;state.offsets[i]=(state.offsets[i]+direction*SPEED*dt/1000+max)%max;track.style.transform=`translate3d(${-state.offsets[i]}px,0,0)`});requestAnimationFrame(animate)}
function openModal(id){const x=state.filtered.find(w=>w.id===id);if(!x)return;const i=state.filtered.indexOf(x);modalImage.onerror=()=>{modalImage.onerror=null;modalImage.src=FALLBACK_IMAGE};modalImage.src=x.image;modalImage.alt=x.title;modalTitle.textContent=`${x.title} / ${x.location} / ${x.year}`;modalCounter.textContent=`${String(i+1).padStart(3,"0")} / ${String(state.filtered.length).padStart(3,"0")}`;modalDescription.textContent=x.description;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("locked")}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true");document.body.classList.remove("locked")}
document.querySelectorAll(".filter-button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".filter-button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;render()}));pauseButton?.addEventListener("click",()=>{state.paused=!state.paused;pauseButton.textContent=state.paused?"Resume motion":"Pause motion"});document.getElementById("modalClose")?.addEventListener("click",closeModal);modal?.addEventListener("click",e=>{if(e.target===modal)closeModal()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});document.getElementById("menuButton")?.addEventListener("click",()=>document.getElementById("mobileMenu")?.classList.toggle("open"));
async function load(){try{const r=await fetch("./works.json?v=9");if(!r.ok)throw Error("works.json unavailable");state.works=await r.json();render();requestAnimationFrame(animate)}catch(e){rows.innerHTML="<p class='works-note'>Unable to load the photo archive.</p>";console.error(e)}}
showView(location.hash.slice(1)||"home");load();
